version: '3'

services:
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver --insecure 0.0.0.0:80"
    container_name: whereami
    volumes:
      - .:/code
    links:
      - postgresql:db
      - redis:redis
    depends_on: 
      - postgresql
      - redis
    ports: 
      - "80:80"
  postgresql:
    image: postgres
    container_name: "whereami-postgresql"
    environment:
      - "POSTGRES_USER=whereami"
      - "POSTGRES_PASSWORD=whereami"
      - "POSTGRES_DB=whereami"
    ports:
      - "5432:5432"
  redis:
    image: redis:5
    expose:
      - "6379"
