version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    container_name: whereami
    volumes:
      - .:/code
    links:
      - postgresql:db
    depends_on: 
      - postgresql
    ports: 
      - "80:80"
  postgresql:
    image: postgres
    container_name: "whereami-postgresql"
    environment:
      - "POSTGRES_USER=whereami"
      - "POSTGRES_PASSWORD=whereami"
      - "POSTGRES_DB=whereami"
    expose: 
      - "5432"